identidock:
    build: .
    ports:
        - "9090:9090"
        - "9191:9191"
        - "5000:5000"
    volumes:
        - ./app:/app
    links:
        - dnmonster
        - redis
    environment: 
        ENV: DEV

dnmonster:
    image: amouat/dnmonster:1.0

redis:
    image: redis:3.0